JustinTulloss/zeromq.node

perf/local_lat.js

Closing the socket to fast may lead to data to be not send.
Something similar is done in [remote_thr](https://github.com/JustinTulloss/zeromq.node/blob/master/perf/remote_thr.js#L27L29)

[Perf local_lat]Don't close the socket immediately

---

binding.cc

This allows one to profile a node application that uses this module
Took notes from PR #340 
Should fix issue #171 
The basic strategy is to check return codes from various functions and if the error was an EINTR signal, then simply try again using a while(true) loop.
I didn't break any new tests, but let me know if there is anything I can do to clean this up.

Handle the EINTR return code by ignoreing it and trying what ever we were doing again.

---

lib/index.js
test/socket.zap.js

- no more recursion for arrays in send()
- _flush no longer uses getters (less magic, and should run a bit faster)
- flags are forced to int
- equalized return and break inside flush (which do the same)
The reason for this PR is that it's hopefully a first little step to moving towards a faster, possibly full C++ implementation of flush.

_flush cleanup

---

lib/index.js

Under load a server that sends a response from within the `message` event can cause the `_flush` method to get called recursively, causing a dump.
> node: ../src/node_object_wrap.h:60: static T* node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = node::Buffer]: Assertion `!handle.IsEmpty()' failed.
Aborted (core dumped).
Here is a test that reproduce the error:
```javascript
var cluster = require('cluster')
, zmq = require('../')
, port = 'tcp://127.0.0.1:12345';
if (cluster.isMaster) {
// Fork 5 clients
for (var i = 0; i < 5; i++) cluster.fork();
//router = server
var socket = zmq.socket('router');
socket.identity = 'server' + process.pid;
socket.bind(port, function() {
console.log('Server listening !');
var i = 0;
socket.on('message', function(envelope, data) {
console.log(++i); …
```

Make sure Socket _flush is not getting called recursively

---

.travis.yml
test/socket.push-pull.js

* Removed Node 0.11 from Travis, added Node 0.12 and io.js
* Bumped ZMQ versions used by Travis
* Fixed typo in pause/resume test

Test updates

---

binding.cc

corrects the control flow issue we overlooked in PR #401.
credit for this PR is due to: @kkoopa, see inline comment: https://github.com/JustinTulloss/zeromq.node/pull/401/files#r27674094

return NanThrowErrors

---

package.json

With the release of io.js v2.0.0 and the associated V8 upgrade, install fails:
```
CXX(target) Release/obj.target/zmq/binding.o
In file included from ../binding.cc:37:
In file included from ../node_modules/nan/nan.h:74:
In file included from ../node_modules/nan/nan_new.h:181:
../node_modules/nan/nan_implementation_12_inl.h:172:66: error: too many arguments to function call, expected at most 2, have 4
return v8::Signature::New(v8::Isolate::GetCurrent(), receiver, argc, argv);
~~~~~~~~~~~~~~~~~~                                      ^~~~~~~~~~
/Users/leon/.node-gyp/2.0.0/deps/v8/include/v8.h:4188:3: note: 'New' declared here
static Local<Signature> New(
^
1 error generated.
make: *** [Release/obj.target/zmq/binding.o] Error 1
```
Bumping nan version fixes the issue.

bump nan version for io.js 2.x compatibility

---

Makefile
package.json

This makes it easier to test in Windows

Allow npm test without depending on "make"

---

binding.cc
lib/index.js
test/exports.js

This is my naive try to address #414. I have no previous experience neither with NaN nor with V8 so please point at my errors and I do my best to address them.
The motivation for the PR is described in the issue referred. I would like to generate the keys needed for Curve without using an external tool and as this method is part oz ZeroMQ since 4.0 I felt it appropriate to put it in to the node binding as well.
I updated the headers in the include folder from [zeromq/zeromq4-x](https://github.com/zeromq/zeromq4-x). I haven't updated the dlls and libs as I couldn't figure out where to get them from.

Adding zmq_curve_keypair to the interface.

---

README.md
appveyor.yml
package.json
test/context.js
test/exports.js
test/socket.router.js

ok this should be a much more [windows-friendly readme with improved install advice](https://github.com/reqshark/zeromq.node/blob/windowsbuild/README.md)
also:
* played around with appveyor matrix settings (need to switch my fork w/ official repo)
* updated the bindings dep in package.json plus a shameless contributor plug
* fixed socket router test by checking platform before err
* skip max number of sockets test with another `require('os').platform()` check

fix windows tests and better install instructions

---

README.md
binding.cc
lib/index.js
test/socket.monitor.js

Currently, on each callback of the monitor timer, only one message is read from the monitor socket, this can lead to a situation where the events reporting start to fall behind.
For example (our case):
* A dealer socker
* The monitor interval is set to 1000ms
* The ZMQ_RECONNECT_IVL is set to 1000ms, so is the ZMQ_RECONNECT_IVL_MAX.
* The server goes down, zmq tries to reconnect, about every 1 second it sends 3 events on the monitor socket (connect_retry, connect_delay, close), but only 1 message is being read (every 1 second), eventually the server goes up, the socket gets reconnected (can see the port is taken), but the monitor events are falling behind and it can take quite some time until the `connected` event will be reached.
This PR makes the following changes:
1. On each monitor …

Read all available monitor messages on each timer callback

---

Makefile

clear the `node_modules` slate in addition to the `build` directory during a `make clean`. good to do in scenarios where you might switch node versions before building

also rm node_modules during clean

---

.travis.yml

Dropped support for io.js in .travis.yml, and added Node.js 4 and 5.

Test against Node 4 and 5

---

.travis.yml

@ronkorving let's just get rid of it
Notice: anyone using node 0.8 needs to upgrade

drop support and coverage for node 0.8

---

binding.cc
lib/index.js
test/socket.events.js
test/socket.messages.js
test/socket.monitor.js
test/socket.pair.js
test/socket.pub-sub.js
test/socket.push-pull.js
test/socket.req-rep.js
test/socket.router.js
test/socket.stream.js
test/socket.unbind.js
test/socket.zap.js
test/zmq_proxy.push-pull.js
test/zmq_proxy.router-dealer.js
test/zmq_proxy.xpub-xsub.js
test/zmq_proxy.xrep-xreq.js

This PR almost triples the throughput on the perf test. Buffers are *still* being copied when sent, so there's still room for improvement, but I would say this is a nice start. Review very welcome (cc @kkoopa @reqshark, @gtamas), please be rigorous.
Benchmark before:
```
$ make perf
node perf/local_lat.js tcp://127.0.0.1:5555 1 100000& node perf/remote_lat.js tcp://127.0.0.1:5555 1 100000
started receiving
message size: 1 [B]
roundtrip count: 100000
mean latency: 0.0733293089 [msecs]
overall time: 14 secs and 665861780 nanoseconds
node perf/local_thr.js tcp://127.0.0.1:5556 1 100000& node perf/remote_thr.js tcp://127.0.0.1:5556 1 100000
started receiving
message size: 1 [B]
message count: 100000
mean throughput: 40431 [msg/s]
mean throughput: 0 [Mbit/s]
overall time: 2 secs and 473361003 …
```

Massive perf boost

---

test/exports.js

Detection copied from the `zap` test.

Skip curve export test if libsodium is missing

---

lib/index.js
test/socket.error-callback.js

Fixes #512 
A bad flags check was causing batches to not be sized correctly (also making the final send() callback drop outside of the batch). This fixes that.
Performance seems unchanged. If anything, maybe a tiny bit faster.

Fixes batch isClosed check

---

package.json

This allows compilation on latest node versions
Maybe I should also expand the  testing matrix to include latest node versions?
Closes #514

Bump NAN to 2.2.0

---

package.json

This gets rid of deprecation warnings introduced in Node 6.

Bump NAN to 2.3

---

binding.cc
test/socket.monitor.js

Fixes #382
When experiencing this crash, the s->monitor_handle_ was not NULL as anticipated (it was 0x31, an invalid pointer, apparently garbage data) and so the check failed and it called uv_timer_start anyway.
Socket::UV_MonitorCallback should be checking the socket status, which is what this PR does.  What's not clear to me is if this should happen before or after processing any pending events.  I put it before just for safety's sake (and because emitted events on a closed socket are probably unwanted).

skip monitoring callback if socket has been closed

---

test/socket.monitor.js

As mentioned in #561, on OS X with homebrewed zeromq the tests are failing quite often.
@ronkorving I don't know if this is a bug that should be fixed properly. If so this PR should provide a hint on what's failing.
<details>
<summary>The full error message from master is here (expand me):</summary>
```
39 passing (21s)
15 failing
1) socket.monitor should use default interval and numOfEvents:
Error: timeout of 2000ms exceeded
at Timeout.<anonymous> (/Users/lukasgeiger/code/zeromq.node/node_modules/mocha/lib/runnable.js:165:14)
at tryOnTimeout (timers.js:232:11)
at Timer.listOnTimeout (timers.js:202:5)
2) socket.monitor should read multiple events on monitor interval:
Error: timeout of 2000ms exceeded
at Timeout.<anonymous> (/Users/lukasgeiger/code/zeromq.node/node_modules/mocha/lib/runnabl …
```

Fix monitor test

---

package.json

This removes the deprecation warning:
`child_process: customFds option is deprecated, use stdio instead.`

Bump dependencies to fix deprecation warning

---

package.json

A 10min timeout is far to long.
Since we are using `travis_retry` when running the tests a short timeout won't cause accidental failures.

Reduce mocha timeout

---

lib/index.js
test/socket.pub-sub.js

If error is thrown in message event handler and error event handler is attached to socket, `_flushRead` is called until no more messages are read.

Fix socket stops receiving messages (#558)

---

binding.cc
lib/index.js
test/socket.monitor.js

Events emitted due to socket monitoring may represent an error, and currently only return the numeric errno.  The binding has a method to translate these to the string that `zmq_strerror` provides but this is not exposed.  Add one, and use it to provide the exception it generates to the callback.
I don't love the function signature to the event callback with this change, but I wrote it that way to be backwards compatible.  If you have a better suggestion, I'm open to ideas.

if an event is an error, pass the exception object

---

lib/index.js

The following code snippet demonstrates that proxy is only forwarding the first part of a multipart message:
```node
let zmq = require('zmq');
let subs = zmq.socket('xpub');
let pubs = zmq.socket('xsub');
subs.bindSync('tcp://127.0.0.1:3000');
pubs.bindSync('tcp://127.0.0.1:3001');
console.log('Proxy bound to to ports 3000 and 3001');
zmq.proxy(subs, pubs);
let subscriber = zmq.socket('sub');
subscriber.connect('tcp://127.0.0.1:3000');
subscriber.subscribe('');
console.log('Subscriber connected to port 3000');
subscriber.on('message', function (part1, part2) {
console.log(part1.toString(), ':', part2 && part2.toString());
});
let publisher = zmq.socket('pub');
publisher.connect('tcp://127.0.0.1:3001');
console.log('Publisher connected to port 3001');
setInterval(() => { …
```

Fix multipart messages for xpub/xsub
